### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jessrod11** [nss-evening-cohort-7/bandz-justin-thyme#1]
# Story
 “ As a developer, in order to create a band member site, we will need to generate 5 html sites, main.js, main.css, and consistent class/id names.

# Acceptance Criteria
**When** - the developer pulls down the branch
**Then**- there should be 5 html files, a main.js, and main.css
**And** common class/id names

# Technical Notes
 - index.html
 - band-members.html
 - news.html
 - tour-schedule.html
 - media.html
- main.js linked to each page```console.log('justin-thyme')```
- main.js should include universal printToDom function
`` function printToDom (stringToPrint, divID){
        var thingToPrint = document.getElementById(divID);
        thingToPrint.innerHTML += stringToPrint;
} ``
- main.css linked to each page. ```background-color: black; color: white;``` 
- google font linked to each page.

**Comment by lolasimp** [comment]
👍
