### ISSUE TITLE
HomePage-Bio

### ISSUE THREAD

**Issue by leotaylor** [nss-evening-cohort-7/bandz-justin-thyme#12]

**Comment by leotaylor** [comment]
# Story
As a user, in order to learn about the band, I need to read some biographical information. 

# Acceptance Criteria 
**When** the user scrolls below the photo container,
**then** they should see a container with a short bio about the band
**if** it is long, then the user should be a able to scroll within the container. 

# Technical Notes
- aligned left and below the photo container
- roughly same size as other containers

**Comment by leotaylor** [comment]
<img width="562" alt="screen shot 2018-03-12 at 9 24 08 pm" src="https://user-images.githubusercontent.com/36465689/37379410-5da7f264-2701-11e8-924f-8fecd69dd296.png">

**Comment by lolasimp** [comment]
👍
