### ISSUE TITLE
Homepage-Styling

### ISSUE THREAD

**Issue by leotaylor** [nss-evening-cohort-7/bandz-justin-thyme#19]

**Comment by leotaylor** [comment]
# Story 
As a developer, in order for my page to look good and be cohesive with the rest of the site, then I need to style the page with CSS. 

# Acceptance Criteria
**When** the page loads
**then** the page should be laid out in a simple easy to read format
**and** have a clear separation from main image to the rest of the content on the page


#Technical Notes
- the 4 containers in the content area should be evenly spaced
- 2 rows and 2 columns
- Top Left: PHOTO
- Top Right: Video
- Bottom Right: Tour
- Bottom Left: Bio
- Containers should all be same size
- Background Color - black 
- font WHITE, HELVETICA UPPERCASE
- bio font include lower case and uppercase

**Comment by leotaylor** [comment]
<img width="562" alt="screen shot 2018-03-12 at 9 24 08 pm" src="https://user-images.githubusercontent.com/36465689/37379350-2acc1a00-2701-11e8-9716-9e3a8849e33c.png">

**Comment by lolasimp** [comment]
Are you gonna close this? 👍
