### ISSUE TITLE
HomePage Jumbo Tron

### ISSUE THREAD

**Issue by leotaylor** [nss-evening-cohort-7/bandz-justin-thyme#5]

**Comment by leotaylor** [comment]
# Story 
as a user, in order to be amazed, I need to see a totally rad "jumbo-tron" like image and band logo. 

# Acceptance Criteria 
**When** the user loads the page
**Then** they should see a justin-thyme logo over an image.
**and** it should take up the browser screen before scrolling down

# Technical notes 
- in index.html
- set a div container that contains the jumbotron image and logo
- use google font aguafina (lowercase)
- keep in mind there will be a nav bar between jumbotron and the rest of the front page content
- use the mountain image, maybe the clocks

**Comment by leotaylor** [comment]
<img width="562" alt="screen shot 2018-03-12 at 9 24 08 pm" src="https://user-images.githubusercontent.com/36465689/37379374-3ded9f5a-2701-11e8-8d3e-5c20818c607b.png">

**Comment by lolasimp** [comment]
👍
