### ISSUE TITLE
HomePage Photo

### ISSUE THREAD

**Issue by leotaylor** [nss-evening-cohort-7/bandz-justin-thyme#7]

**Comment by leotaylor** [comment]
# As a user, in order to see an image of the band, I need to include an image of the band. 

# Acceptance Criteria 
**When** the user scrolls down
**then** they should see an image aligned to the left of the band

# Technical Notes
- the image should be in a container with div id "bandPhoto"
- aligned top left, but below jumbotron 
- should be roughly the same size of the three other div containers 
- hard coded
-stretch goal ---- multiple photos to scroll through

**Comment by leotaylor** [comment]
<img width="562" alt="screen shot 2018-03-12 at 9 24 08 pm" src="https://user-images.githubusercontent.com/36465689/37379382-49a1cd12-2701-11e8-9313-5f320c981297.png">

**Comment by lolasimp** [comment]
👍
