### ISSUE TITLE
Research Media Tags

### ISSUE THREAD

**Issue by leotaylor** [nss-evening-cohort-7/bandz-justin-thyme#8]

**Comment by leotaylor** [comment]
# Story 
As a developer, in order to add a video to home page, I need to refresh my knowledge on the media tags.

# Acceptance Criteria
**When** I have finished research the methods for adding a video,
**then** I should be able to add a video to the page. 

# Technical Notes
- https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe
- https://www.w3schools.com/html/html5_video.asp

**Comment by leotaylor** [comment]
I have learned

**Comment by lolasimp** [comment]
👍
